language: php
php:
  - "5.6"
  - "5.5"
  - "5.4"
  - "5.3"
  - "hhvm"
script: phpunit --bootstrap tests/autoload.php -c tests.xml
notifications:
  email:
    on_success: change
    on_failure: change
